name: GitHub Snake Game

on:
  # Atualiza a animação todos os dias às 00:00 UTC
  schedule:
    - cron: "0 0 * * *"

  # Permite executar manualmente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Faz checkout do código
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # Gera a animação da cobrinha
      - name: Gera animação Snake
        uses: Platane/snk@v3
        with:
          github_user_name: alveshenriique
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake.gif?color_snake=#FF4500&color_dots=#aad8ff,#6fb1fc,#368cf9,#0e6bfd,#0046ad
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Publica na branch output
      - name: Publica na branch output
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
